-- COPIE E COLE ESTE CÓDIGO NO SQL EDITOR DO SUPABASE

-- 1. Cria a tabela de reservas e encomendas
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  date text not null,
  time text not null,
  guests text not null,
  type text not null, -- 'reserva' ou 'encomenda'
  status text default 'pendente', -- 'pendente', 'confirmado', 'cancelado'
  notes text
);

-- 2. Habilita segurança (Row Level Security)
alter table public.reservations enable row level security;

-- 3. Cria políticas de acesso (necessário para funcionar com a chave pública do site)

-- Permitir que qualquer pessoa (anon) crie uma reserva (Insert)
create policy "Enable insert for everyone" 
on public.reservations for insert 
to anon 
with check (true);

-- Permitir leitura (necessário para o seu Dashboard Administrativo ver os pedidos)
create policy "Enable select for everyone" 
on public.reservations for select 
to anon 
using (true);

-- Permitir atualização (necessário para o Dashboard Administrativo aprovar/recusar)
create policy "Enable update for everyone" 
on public.reservations for update 
to anon 
using (true);