-- --- INSTRUÇÕES IMPORTANTES ---
-- 1. Copie todo este conteúdo.
-- 2. Vá no painel do Supabase (SQL Editor).
-- 3. Cole e clique em "RUN".
-- ------------------------------

-- 1. Cria a tabela (com a nova coluna file_url)
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  date text not null,
  time text not null,
  guests text not null,
  type text not null, -- 'reserva' ou 'encomenda'
  status text default 'pendente',
  notes text,
  file_url text -- Link para o PDF do comprovativo
);

-- 2. Permissões de Tabela (GRANTS)
grant usage on schema public to anon, authenticated;
grant all on table public.reservations to anon, authenticated;
grant usage, select on sequence public.reservations_id_seq to anon, authenticated;

-- 3. Segurança da Tabela (RLS)
alter table public.reservations enable row level security;

-- Limpa regras antigas de Tabela
drop policy if exists "Universal Access Policy" on public.reservations;
drop policy if exists "Public Access" on public.reservations;

-- Regra de Tabela: Permitir tudo para todos (Leitura, Escrita, Exclusão)
create policy "Universal Access Policy"
on public.reservations
for all
to public
using (true)
with check (true);

-- 4. CONFIGURAÇÃO DE STORAGE (Para o PDF)
-- Tenta criar o bucket 'receipts' se não existir
insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', true)
on conflict (id) do nothing;

-- Limpa regras antigas de Storage para evitar conflitos
drop policy if exists "Public Access Receipts" on storage.objects;
drop policy if exists "Public Upload Receipts" on storage.objects;
drop policy if exists "Give me access to receipts" on storage.objects;

-- Regra de Storage: Permitir upload público no bucket receipts
create policy "Public Upload Receipts"
on storage.objects for insert
to public
with check (bucket_id = 'receipts');

-- Regra de Storage: Permitir leitura pública no bucket receipts
create policy "Public Read Receipts"
on storage.objects for select
to public
using (bucket_id = 'receipts');

-- Regra de Storage: Permitir deletar (opcional, para admin limpar depois se quiser via API)
create policy "Public Delete Receipts"
on storage.objects for delete
to public
using (bucket_id = 'receipts');

select 'Banco de dados e Storage configurados com sucesso!' as mensagem;