-- COPIE E COLE ESTE CÓDIGO NO SQL EDITOR DO SUPABASE E CLIQUE EM "RUN"

-- 1. Garante que a tabela existe
create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text not null,
  date text not null,
  time text not null,
  guests text not null,
  type text not null, -- 'reserva' ou 'encomenda'
  status text default 'pendente', -- 'pendente', 'confirmado', 'cancelado'
  notes text
);

-- 2. Habilita o sistema de segurança (RLS)
alter table public.reservations enable row level security;

-- 3. LIMPEZA: Remove políticas antigas para evitar conflitos
drop policy if exists "Enable insert for everyone" on public.reservations;
drop policy if exists "Enable full access for authenticated users" on public.reservations;
drop policy if exists "Enable select for everyone" on public.reservations;
drop policy if exists "Enable update for everyone" on public.reservations;
drop policy if exists "Enable all for everyone" on public.reservations;

-- 4. CRIAÇÃO DE NOVAS POLÍTICAS (PERMISSIVAS)

-- Política ÚNICA: Permite TUDO (Insert, Select, Update, Delete) para TODOS (Anon e Authenticated)
-- Isso resolve o erro "row-level security policy" e garante que o Admin veja os dados mesmo se o login falhar.
create policy "Enable all for everyone" 
on public.reservations 
for all 
to anon, authenticated 
using (true) 
with check (true);
